language: java
jdk: oraclejdk8

env:
  global:
  - secure: T49h8KN1yVL89y7BD0L8yhQw+MZuerj9sEzbh1dX4DaNJ90ZSmdnm7VaAksu7e/sb8t2VkB37T4SGEJdDnHGGbY1bVhTqMt0Aikb+RQFPbzC/OWuTEkp9C4EvCMuAPlMnftqvgl9rrJDXh9fwWsrcLNaBiQ2i3CQiPlau0jVWFg=
  - secure: V11tTip7AJuwuoCOhH5wlPH4Qx08BuxmnhIQzawtMEMOL/sL27S7n8bC/XFL4WFgvwH3SCYnis3kT5eqkocZc1QVKEgdOZPoaUUZPyJ4NckvTT3i/EV7172neNsZunyQ7BKjFGyV0AGNQ2kNuUgfBA15Wh+KXeyWcgtYNSLL0jc=

after_success: ./.travis/artifact-upload.sh
